version = 0.1
[default.deploy.parameters]
stack_name = "spring-demo"
resolve_s3 = true
s3_prefix = "spring-demo"
region = "ap-southeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
